"""Updating User and Question Model

Revision ID: 39f682ecfd5e
Revises: 
Create Date: 2021-10-23 20:33:42.868452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f682ecfd5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('firstname', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('type_user', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type_user')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.drop_column('questions', 'score')
    # ### end Alembic commands ###
